#!/usr/bin/env zsh 
switch_to() {
    if [[ -z $TMUX ]]; then
        tmux attach-session -t $1
    else
        tmux switch-client -t $1
    fi
}

has_session() {
    tmux list-sessions | grep -q "^$1:"
}

hydrate() {
    tmux send-keys -t $1 "source $HOME/.zsh/scripts/tmux-sessionizer-init" c-M
}

if [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$(find ~ ~/Documents -mindepth 1 -maxdepth 1 -type d | fzf --layout reverse)
fi

if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

if ! has_session $selected_name; then
    tmux new-session -ds $selected_name -c $selected
    hydrate $selected_name $selected
fi

switch_to $selected_name
